
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - trading-network

  exchange:
    build: ./Exchange
    container_name: exchange
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    networks:
      - trading-network
  
networks:
  trading-network:
    driver: bridge